# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'simulacion.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(621, 556)
        self.verticalLayout = QtGui.QVBoxLayout(Form)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBox_2 = QtGui.QGroupBox(Form)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_3 = QtGui.QLabel(self.groupBox_2)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_3.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_3.addWidget(self.label_4, 1, 0, 1, 1)
        self.lblDemandaAcumulada = QtGui.QLabel(self.groupBox_2)
        self.lblDemandaAcumulada.setObjectName(_fromUtf8("lblDemandaAcumulada"))
        self.gridLayout_3.addWidget(self.lblDemandaAcumulada, 0, 1, 1, 1)
        self.lblDemandaDiaria = QtGui.QLabel(self.groupBox_2)
        self.lblDemandaDiaria.setObjectName(_fromUtf8("lblDemandaDiaria"))
        self.gridLayout_3.addWidget(self.lblDemandaDiaria, 1, 1, 1, 1)
        self.lblEventoDemandaDiaria = QtGui.QLabel(self.groupBox_2)
        self.lblEventoDemandaDiaria.setText(_fromUtf8(""))
        self.lblEventoDemandaDiaria.setObjectName(_fromUtf8("lblEventoDemandaDiaria"))
        self.gridLayout_3.addWidget(self.lblEventoDemandaDiaria, 1, 2, 1, 1)
        self.lvlEventoDemandaAcumulada = QtGui.QLabel(self.groupBox_2)
        self.lvlEventoDemandaAcumulada.setText(_fromUtf8(""))
        self.lvlEventoDemandaAcumulada.setObjectName(_fromUtf8("lvlEventoDemandaAcumulada"))
        self.gridLayout_3.addWidget(self.lvlEventoDemandaAcumulada, 0, 2, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.groupBox = QtGui.QGroupBox(Form)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.lblEventoSockAutoparte1 = QtGui.QLabel(self.groupBox)
        self.lblEventoSockAutoparte1.setObjectName(_fromUtf8("lblEventoSockAutoparte1"))
        self.gridLayout_2.addWidget(self.lblEventoSockAutoparte1, 0, 2, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.lblStockAutoparte2 = QtGui.QLabel(self.groupBox)
        self.lblStockAutoparte2.setObjectName(_fromUtf8("lblStockAutoparte2"))
        self.gridLayout_2.addWidget(self.lblStockAutoparte2, 1, 1, 1, 1)
        self.lblStockAutoparte1 = QtGui.QLabel(self.groupBox)
        self.lblStockAutoparte1.setObjectName(_fromUtf8("lblStockAutoparte1"))
        self.gridLayout_2.addWidget(self.lblStockAutoparte1, 0, 1, 1, 1)
        self.lblEventoAutoparte2l = QtGui.QLabel(self.groupBox)
        self.lblEventoAutoparte2l.setObjectName(_fromUtf8("lblEventoAutoparte2l"))
        self.gridLayout_2.addWidget(self.lblEventoAutoparte2l, 1, 2, 1, 1)
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.groupBox_3 = QtGui.QGroupBox(Form)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.lblStockAutoparte2_3 = QtGui.QLabel(self.groupBox_3)
        self.lblStockAutoparte2_3.setObjectName(_fromUtf8("lblStockAutoparte2_3"))
        self.gridLayout_5.addWidget(self.lblStockAutoparte2_3, 1, 1, 1, 1)
        self.lblEventoStockAutoparte1 = QtGui.QLabel(self.groupBox_3)
        self.lblEventoStockAutoparte1.setObjectName(_fromUtf8("lblEventoStockAutoparte1"))
        self.gridLayout_5.addWidget(self.lblEventoStockAutoparte1, 0, 2, 1, 1)
        self.label_8 = QtGui.QLabel(self.groupBox_3)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_5.addWidget(self.label_8, 0, 0, 1, 1)
        self.label_9 = QtGui.QLabel(self.groupBox_3)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_5.addWidget(self.label_9, 1, 0, 1, 1)
        self.lblStockAutoparte1_3 = QtGui.QLabel(self.groupBox_3)
        self.lblStockAutoparte1_3.setObjectName(_fromUtf8("lblStockAutoparte1_3"))
        self.gridLayout_5.addWidget(self.lblStockAutoparte1_3, 0, 1, 1, 1)
        self.lblEventoStockAutoparte2 = QtGui.QLabel(self.groupBox_3)
        self.lblEventoStockAutoparte2.setObjectName(_fromUtf8("lblEventoStockAutoparte2"))
        self.gridLayout_5.addWidget(self.lblEventoStockAutoparte2, 1, 2, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_15 = QtGui.QLabel(Form)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout.addWidget(self.label_15)
        self.lblDiaMesAnio = QtGui.QLabel(Form)
        self.lblDiaMesAnio.setObjectName(_fromUtf8("lblDiaMesAnio"))
        self.horizontalLayout.addWidget(self.lblDiaMesAnio)
        self.lblDiaMesAnioFinal = QtGui.QLabel(Form)
        self.lblDiaMesAnioFinal.setObjectName(_fromUtf8("lblDiaMesAnioFinal"))
        self.horizontalLayout.addWidget(self.lblDiaMesAnioFinal)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.groupBox_2.setTitle(_translate("Form", "Demanda", None))
        self.label_3.setText(_translate("Form", "Acumulada", None))
        self.label_4.setText(_translate("Form", "Diaria", None))
        self.lblDemandaAcumulada.setText(_translate("Form", "100", None))
        self.lblDemandaDiaria.setText(_translate("Form", "20", None))
        self.groupBox.setTitle(_translate("Form", "Deposito", None))
        self.lblEventoSockAutoparte1.setText(_translate("Form", "+ 160 ", None))
        self.label_2.setText(_translate("Form", "autoparte 2", None))
        self.lblStockAutoparte2.setText(_translate("Form", "1500", None))
        self.lblStockAutoparte1.setText(_translate("Form", "2000", None))
        self.lblEventoAutoparte2l.setText(_translate("Form", "+ 110", None))
        self.label.setText(_translate("Form", "autoparte 1", None))
        self.groupBox_3.setTitle(_translate("Form", "Empleados", None))
        self.lblStockAutoparte2_3.setText(_translate("Form", "1500", None))
        self.lblEventoStockAutoparte1.setText(_translate("Form", "+ 160 ", None))
        self.label_8.setText(_translate("Form", "autoparte 1", None))
        self.label_9.setText(_translate("Form", "autoparte 2", None))
        self.lblStockAutoparte1_3.setText(_translate("Form", "2000", None))
        self.lblEventoStockAutoparte2.setText(_translate("Form", "+ 123", None))
        self.label_15.setText(_translate("Form", "Dia", None))
        self.lblDiaMesAnio.setText(_translate("Form", "1 / 2 / 1 ", None))
        self.lblDiaMesAnioFinal.setText(_translate("Form", "30 - 12 - 5", None))

